defmodule HologramSkeleton.Repo.Migrations.Initial do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:articles, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :slug, :text, null: false
      add :title, :text, null: false
      add :description, :text, null: false
      add :body_raw, :text, null: false, default: ""
      add :body, :text, null: false

      add :created_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")

      add :updated_at, :utc_datetime_usec,
        null: false,
        default: fragment("(now() AT TIME ZONE 'utc')")
    end

    create unique_index(:articles, [:slug], name: "articles_unique_slug_index")
  end

  def down do
    drop_if_exists unique_index(:articles, [:slug], name: "articles_unique_slug_index")

    drop table(:articles)
  end
end
